#! /bin/bash
# This file is managed by puppet. Manual changes will be reverted on the next puppet run.

export RUBY_HEAP_MIN_SLOTS=3500000
export RUBY_HEAP_SLOTS_INCREMENT=250000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_HEAP_FREE_MIN=350000
export RUBY_GC_MALLOC_LIMIT=1000000000

#export RUBY_GC_STATS=1
#export RUBY_GC_DATA_FILE=/tmp/ruby_gc.txt

exec "/usr/bin/ruby" "$@"
